name: CI
'on':
  push:
    branches:
    - main
jobs:
  testy:
    runs-on: ubuntu-latest
    steps:
    - name: Pobierz kod
      uses: actions/checkout@v4
    - name: Ustaw Pythona
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Zainstaluj zaleznosci
      run: pip install -r requirements.txt
    - name: Uruchom testy
      run: pytest cwiczenia -v
